### PR TITLE
Support dart2 stable

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Comment by devoncarew** [comment]
We may want to consider removing the travis build instead. This is unsupported and may or may not work in Dart 2.

cc @sigmundch

**Comment by sigmundch** [comment]
Agree - I don't believe this has been updated in a long long time, and I don't believe the code is Dart2 compliant.

**Comment by kevmoo** [comment]
https://pub.dartlang.org/packages?q=dependency%3Acompiler_unsupported

No one uses it. Should we archive and mark it deprecated on the pub site?

**Pull request closed without merging**
